sudo: required

# language: node_js
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.8.0
# before_install:
#   - sudo apt-get update
#   - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
#   - docker-compose --version
#   - sudo rm /usr/local/bin/docker-compose
#   - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#   - chmod +x docker-compose
#   - sudo mv docker-compose /usr/local/bin
#   - docker-compose --version
#
#   # Setup your application stack. You may need to tweak these commands if you
#   # doing out-of-the-ordinary docker-compose builds.
#   - docker-compose pull
#   - docker-compose build
#   - docker-compose start
#
#   - docker ps
#

before_install:
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker-compose pull
  - docker-compose build

before_script:
  - docker-compose up -d

script:
  - docker-compose exec api yarn
  - docker-compose exec api yarn run test

after_script:
  - docker-compose down
